blank_issues_enabled: false
contact_links:
  - name: Stock Trader community chat
    url: https://gitter.im/IBMStockTrader/community
    about: Ask general questions and collaborate with other contributors.

