org.eclipse.microprofile.rest.client.propagateHeaders=Authorization,Proxy-Authorization
otel.sdk.disabled=false
otel.exporter.otlp.endpoint=http://jaeger-collector.istio-system.svc.cluster.local:4317
MAX_ORDER_NOTIONAL=1000000.00
MAX_POSITION_NOTIONAL=5000000.00
FAT_FINGER_NOTIONAL_THRESHOLD=2500000.00
RESTRICTED_SYMBOLS=RSTRA,RSTRB
EXCEPTION_SLA_HOURS=24
